Repository erikfille/PF-Henry, pull requests merged in 2023-03, with the labels that each got.

#1 Erik
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/index.css
  client/src/main.jsx
  client/vite.config.js
Labels: enhancement

#4 testing commit
  api/src/models/productos_servicios/Producto_servicio.js
Labels: enhancement

#5 commit testing2
  api/src/models/comentarios_reseñas/Comentario_reseña.js
Labels: enhancement

#7 Basic Routing added
  client/src/App.jsx
Labels: enhancement

#8 Petri
  api/src/models/envios/Envio.js
  api/src/models/envios/envios.json
  api/src/models/ordenesDeCompras/OrdenDeCompra.js
  api/src/models/ordenesDeCompras/ordenesDeCompras.json
Labels: enhancement

#9 Jhon
  api/src/app.js
  api/src/models/roles/Rol.js
  api/src/models/roles/roles.json
  api/src/models/usuarios/Usuario.js
  api/src/models/usuarios/usuarios.json
Labels: enhancement

#10 agregando nuevo modelo, mascotas
  api/src/models/mascotas/Mascota.js
  api/src/models/mascotas/mascota.json
Labels: enhancement

#12 Santi
  api/src/app.js
  api/src/database.js
  api/src/models/categorias/Categoria.js
  api/src/models/categorias/categorias.json
  api/src/models/comentarios_reseñas/Comentario_reseña.js
  api/src/models/comentarios_reseñas/comentarios_reseñas.json
  api/src/models/productos_servicios/Producto_servicio.js
  api/src/models/productos_servicios/productos_servicios.json
Labels: enhancement

#13 Noe
  client/package-lock.json
  client/src/App.css
  client/src/App.jsx
  client/src/Views/About/About.jsx
  client/src/Views/CartEmpty/CartEmpty.jsx
  client/src/Views/CartProducts/CartProducts.jsx
  client/src/Views/Checkout/Checkout.jsx
  client/src/Views/Checkout/Checkout.module.css
  client/src/Views/Detail/Detail.jsx
  client/src/Views/Detail/Detail.module.css
  client/src/Views/Footer/Footer.jsx
  client/src/Views/ForgotPassword/ForgotPassword.jsx
  client/src/Views/Main/Main.jsx
  client/src/Views/PerfilUser/PerfilUser.jsx
  client/src/Views/SignUp/SignUp.jsx
  client/src/Views/Store/Store.jsx
  client/src/Views/Tienda/Tienda.jsx
  client/src/Views/Tienda/Tienda.module.css
  client/src/Views/UserPetsDetail/UserPetDetail.jsx
  client/src/Views/UserPetsDetail/UserPetDetail.module.css
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/Views/UserProfile/UserProfile.module.css
  client/src/components/Accordion/Accordion.jsx
  client/src/components/Accordion/Accordion.modules.css
  client/src/components/AdressForm/AdressForm.jsx
  client/src/components/AdressForm/AdressForm.module.css
  client/src/components/BreadCrumb/BreadCrumb.jsx
  client/src/components/BreadCrumb/BreadCrumb.module.css
  client/src/components/Cart/Cart.jsx
  client/src/components/Cart/Cart.module.css
  client/src/components/FilterBy/Filter.jsx
  client/src/components/FilterBy/Filter.module.css
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.module.css
  client/src/components/Paginate/Paginate.jsx
  client/src/components/Paginate/Paginate.module.css
  client/src/components/PayMethodForm/PayMethodForm.jsx
  client/src/components/PayMethodForm/PayMethodForm.module.css
  client/src/components/PetData/PetData.jsx
  client/src/components/PetData/PetData.module.css
  client/src/components/PetDetail/PetDetail.jsx
  client/src/components/PetDetail/PetDetail.module.css
  client/src/components/ProductCard/ProductCart.jsx
  client/src/components/ProductCard/ProductCart.module.css
  client/src/components/ProductDetaild/ProductDetail.jsx
  client/src/components/ProductDetaild/ProductDetail.module.css
  client/src/components/Reseñas/Reseñas.jsx
  client/src/components/Reseñas/Reseñas.module.css
  client/src/components/SearchBar/SearchBar.jsx
  client/src/components/SearchBar/SearchBar.module.css
  client/src/components/ServiceCard/ServiceCard.jsx
  client/src/components/ServiceCard/ServiceCard.module.css
  client/src/components/ShopHistory/ShopHistory.jsx
  client/src/components/ShopHistory/ShopHistory.module.css
  client/src/components/SideBar/SideBar.jsx
  client/src/components/SideBar/SideBar.module.css
  client/src/components/Team/Team.jsx
  client/src/components/Team/Team.module.css
  client/src/components/UserData/UserData.jsx
  client/src/components/UserData/UserData.module.css
Labels: enhancement

#14 Footer finished
  client/src/App.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.module.css
Labels: enhancement

#15 Merge con conflictos con commit de Noe
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Views/Login/Login.jsx
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/hooks/useAuth.js
  client/src/hooks/useStore.js
  client/src/main.jsx
  client/src/mixins/auth.js
Labels: enhancement

#17 Santi
  api/src/app.js
  api/src/models/roles/Rol.js
  api/src/models/roles/roles.json
  api/src/models/usuarios/Usuario.js
  api/src/models/usuarios/usuarios.json
  api/src/routes/roles.js
  api/src/routes/text.txt
  api/src/routes/usuarios.js
Labels: enhancement

#18 modelos mascotas y productosV
  api/src/models/mascotas/mascota.js
  api/src/models/mascotas/mascotas.json
  api/src/models/productosVendido/productoVendido.js
  api/src/models/productosVendido/productosVendidos.json
  api/src/models/usuarios/Usuario.js
Labels: enhancement

#19 Santi
  api/src/models/mascotas/mascota.js
  api/src/models/mascotas/mascota.json
  api/src/models/mascotas/mascotas.json
Labels: enhancement

#20 inicio mascotas
  api/src/models/mascotas/Mascota.js
Labels: enhancement

#21 Componente Login con logica básica aplicada
  client/Readme.md
  client/package-lock.json
  client/src/App.jsx
  client/src/Views/Login/Login.jsx
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/components/LoginWidget/validation.js
Labels: enhancement

#23 Petri
  api/src/models/envios/Envio.js
  api/src/models/envios/envios.json
  api/src/models/ordenesDeCompras/OrdenDeCompra.js
  api/src/models/ordenesDeCompras/ordenesDeCompras.json
Labels: bug

#30 Jonathan
  client/package-lock.json
  client/src/App.css
  client/src/Views/Tienda/Tienda.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductsContainer/ProductsContainer.jsx
Labels: enhancement

#31 Santi
  api/src/app.js
  api/src/models/categorias/Categoria.js
  api/src/routes/products.js
Labels: enhancement

#33 CreateProduct added + CloudinaryWidget + React Select
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/CreateProduct/CreateProduct.jsx
  client/src/components/CreateProduct/UploadWidget.jsx
  client/src/components/CreateProduct/validation.js
  client/src/components/LoginWidget/LoginWidget.jsx
Labels: enhancement

#35 Jonathan
  client/public/images/cat-footer.png
  client/src/App.css
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.module.css
Labels: enhancement

#36 Santi
  api/README.md
  api/src/app.js
  api/src/database.js
  api/src/routes/categorias.js
  api/src/routes/productos.js
  api/src/routes/products.js
Labels: enhancement

#37 Santi
  api/src/models/roles/Rol.js
  api/src/models/roles/roles.json
  api/src/routes/usuarios.js
Labels: enhancement

#38 Pasando estilos de app.css a cada archivo module.css
  client/package-lock.json
  client/src/App.css
  client/src/Views/Tienda/Tienda.jsx
  client/src/Views/Tienda/Tienda.module.css
  client/src/components/BreadCrump/BreadCrump.jsx
  client/src/components/BreadCrump/BreadCrump.module.css
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.module.css
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductCard/ProductCard.module.css
Labels: enhancement

#39 creacion y correcion de archivos para rutas
  api/src/app.js
  api/src/routes/allProductos.js
  api/src/routes/createProducto.js
  api/src/routes/productoDetail.js
  api/src/routes/stockProductos.js
Labels: enhancement

#40 Jhon
  api/src/models/mascotas/Mascota.js
  api/src/models/mascotas/mascotas.json
  api/src/models/productosVendido/productoVendido.js
  api/src/models/usuarios/Usuario.js
Labels: enhancement

#41 Petri
  api/src/app.js
  api/src/models/productos_servicios/Producto_servicio.js
  api/src/models/productos_servicios/productos_servicios.json
  api/src/routes/createProducto.js
Labels: enhancement

#44 Petri
  api/src/app.js
  api/src/routes/stockProductos.js
Labels: enhancement

#46 se agrego la ruta PUT
  api/src/routes/usuarios.js
Labels: enhancement

#47 inicio de archivops de rutas proveedor
  api/src/app.js
  api/src/routes/getProveedor.js
  api/src/routes/postProveedor.js
Labels: enhancement

#48 incio de ruta crear mascota
  api/src/app.js
  api/src/routes/createMascota.js
Labels: enhancement

#50 ruta mascotas ok
  api/src/app.js
  api/src/routes/createMascota.js
Labels: enhancement

#49 Noelita
  .DS_Store
  client/src/Views/About/About.jsx
  client/src/Views/About/About.module.css
  client/src/assets/img/profile-Noe.png
Labels: enhancement

#52 correcion de la ruta Crear produtos
  api/src/models/productos_servicios/Producto_servicio.js
  api/src/models/productos_servicios/productos_servicios.json
  api/src/routes/createProducto.js
Labels: enhancement

#53 Agregado al modelo "Proveedor" los cambios propuestos por el front
  api/src/models/provedores/Proveedor.js
Labels: enhancement

#54 correcion de usuario login req por body
  api/src/routes/usuarios.js
Labels: enhancement

#55 Petri
  api/src/app.js
  api/src/models/provedores/Proveedor.js
  api/src/models/provedores/provedores.json
  api/src/routes/postProveedor.js
Labels: enhancement

#56 cositassss
  api/src/app.js
  api/src/models/usuarios/Usuario.js
  api/src/routes/ordenDeCompra.js
Labels: enhancement

#57 Modelo y rutas CATEGORÍAS.
  api/src/models/categorias/Categoria.js
  api/src/models/categorias/categorias.json
  api/src/routes/categorias.js
Labels: enhancement

#58 Probando funciones ordenado y filtrado
  client/src/Views/Tienda/Tienda.jsx
  client/src/Views/Tienda/helper.js
  client/src/components/ProductsContainer/ProductsContainer.jsx
Labels: enhancement

#59 Añadido a la ruta categorias el PUT y el POST.
  api/src/routes/categorias.js
Labels: enhancement

#60 Añadi imgs de perfil
  .DS_Store
  client/src/Views/About/About.jsx
  client/src/assets/img/profile-Noe.png
  client/src/assets/img/profile-pic (10).png
  client/src/assets/img/profile-pic (11).png
  client/src/assets/img/profile-pic (12).png
  client/src/assets/img/profile-pic (13).png
  client/src/assets/img/profile-pic (14).png
  client/src/assets/img/profile-pic (15).png
  client/src/assets/img/profile-pic (16).png
  client/src/assets/img/profile-pic (17).png
  client/src/assets/img/profile-pic (18).png
  client/src/assets/img/profile-pic (19).png
  client/src/assets/img/profile-pic (2).png
  client/src/assets/img/profile-pic (20).png
  client/src/assets/img/profile-pic (3).png
  client/src/assets/img/profile-pic (4).png
  client/src/assets/img/profile-pic (5).png
  client/src/assets/img/profile-pic (6).png
  client/src/assets/img/profile-pic (7).png
  client/src/assets/img/profile-pic (8).png
  client/src/assets/img/profile-pic (9).png
  client/src/assets/img/profile-pic.png
Labels: enhancement

#61 Noelita
  .DS_Store
  client/src/Views/About/About.jsx
  client/src/Views/About/About.module.css
  client/src/assets/img/profile-pic (10).png
  client/src/assets/img/profile-pic (12).png
  client/src/assets/img/profile-pic (13).png
  client/src/assets/img/profile-pic (14).png
  client/src/assets/img/profile-pic (16).png
  client/src/assets/img/profile-pic (17).png
  client/src/assets/img/profile-pic (19).png
  client/src/assets/img/profile-pic (20).png
  client/src/assets/img/profile-pic (3).png
  client/src/assets/img/profile-pic (4).png
  client/src/assets/img/profile-pic (5).png
  client/src/assets/img/profile-pic (7).png
  client/src/assets/img/profile-pic (8).png
  client/src/assets/img/profile-pic (9).png
  client/src/assets/img/profile-pic.png
  client/src/assets/img/profileErik.png
  client/src/assets/img/profileJhon.png
  client/src/assets/img/profileJonha.png
  client/src/assets/img/profileNacho.png
  client/src/assets/img/profileNoe.png
  client/src/assets/img/profilePetri.png
  client/src/assets/img/profileSanti.png
Labels: enhancement

#63 HAPI-CORS
  api/node_modules/.package-lock.json
  api/package-lock.json
  api/package.json
  api/src/routes/categorias.js
Labels: enhancement

#62 Noelita
  client/src/Views/About/About.jsx
  client/src/assets/img/profileErik 2.png
  client/src/assets/img/profileJhon 2.png
  client/src/assets/img/profileJonha 2.png
  client/src/assets/img/profileNacho 2.png
  client/src/assets/img/profileNoe 2.png
  client/src/assets/img/profilePetri 2.png
  client/src/assets/img/profileSanti 2.png
  client/src/components/Paginate/Paginate.jsx
Labels: enhancement

#65 Login logic almost complete
  .gitignore
  api/node_modules/.package-lock.json
  api/src/app.js
  api/src/routes/categorias.js
  client/src/components/CreateProduct/CreateProduct.jsx
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/components/Paginate/Paginate.jsx
  client/src/hooks/useAuth.js
Labels: enhancement

#68 Jonathan
  .DS_Store
  .gitignore
  client/public/images/service-img.jpg
  client/src/App.css
  client/src/Views/Servicios/Servicios.jsx
  client/src/Views/Servicios/Servicios.module.css
  client/src/Views/Servicios/helperService.js
  client/src/Views/Tienda/Tienda.jsx
  client/src/Views/Tienda/Tienda.module.css
  client/src/components/BreadCrump/BreadCrump.jsx
  client/src/components/Header/Header.jsx
  client/src/components/ServiceCard/ServiceCard.jsx
  client/src/components/ServiceCard/ServiceCard.module.css
  client/src/components/ServiceContainer/ServiceContainer.jsx
  client/src/components/ServiceContainer/ServiceContainer.module.css
Labels: enhancement

#69 Ruta GetProveedores
  api/src/app.js
  api/src/routes/getProveedor.js
Labels: enhancement

#70 arreglo model oredbdcompra
  api/src/models/ordenesDeCompras/OrdenDeCompra.js
Labels: enhancement

#71 ultragie abuse y escupi la ruta proveedor de petri
  api/src/models/provedores/Proveedor.js
  api/src/models/provedores/provedores.json
  api/src/routes/getProveedor.js
Labels: enhancement

#72 LoginWidget updated to accept both login & signup
  client/src/App.jsx
  client/src/Views/Login/Login.jsx
  client/src/components/LoginWidget/LoginWidget.jsx
Labels: enhancement

#73 ordenamiento de rutas
  api/src/app.js
  api/src/models/provedores/provedores.json
  api/src/routes/Productos/allProductos.js
  api/src/routes/Productos/createProducto.js
  api/src/routes/Productos/productoDetail.js
  api/src/routes/Productos/stockProductos.js
  api/src/routes/Proveedores/getProveedor.js
  api/src/routes/Proveedores/postProveedor.js
Labels: enhancement

#74 Jonathan
  client/public/images/bg-paw.png
  client/public/images/pets-img.png
  client/src/Views/Home/Home.jsx
  client/src/Views/Home/Home.module.css
Labels: enhancement

#77 Detail View created
  .gitignore
  client/src/App.jsx
  client/src/Views/Detail/Detail.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/ProductDetail/ProductDetail.module.css
  client/src/components/ProductReviews/ProductReviews.jsx
  client/src/components/ProviderDetail/ProviderDetail.jsx
  client/src/components/ProviderDetail/ProviderDetail.module.css
Labels: enhancement

#78 Modificando el modelo de categorías y el post del mencionado.
  api/src/models/categorias/Categoria.js
  api/src/routes/categorias.js
Labels: enhancement

#79 minimas correcciones
  api/src/models/productos_servicios/Producto_servicio.js
  api/src/models/roles/roles.json
  api/src/routes/usuarios.js
Labels: enhancement

#81 Noelita
  .DS_Store
  client/src/Views/About/About.jsx
  client/src/Views/About/About.module.css
  client/src/assets/img/profileMax.png
Labels: enhancement

#82 Conexion de la tienda con Zustand casi finalizada
  client/src/Views/Tienda/Tienda.jsx
  client/src/Views/Tienda/helper.js
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductReviews/ProductReviews.jsx
  client/src/components/ProductsContainer/ProductsContainer.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#83 ruta Search y añadidas x server.route a app.js
  api/src/app.js
  api/src/routes/Productos/searchProducto.js
Labels: enhancement

#84 pequeñas correciones de productos
  api/src/models/productos_servicios/Producto_servicio.js
  api/src/routes/Productos/allProductos.js
  api/src/routes/Productos/createProducto.js
Labels: enhancement

#95 Detail reparado
  client/src/App.jsx
  client/src/Views/Detail/Detail.jsx
  client/src/Views/Home/Home.jsx
  client/src/Views/Tienda/Tienda.jsx
  client/src/components/Cart/Cart.jsx
  client/src/components/Header/Header.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/ProductReviews/ProductReviews.jsx
  client/src/components/ProductsContainer/ProductsContainer.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#97 muchos cambios sobre la hora
  api/src/app.js
  api/src/models/categorias/Categoria.js
  api/src/models/provedores/Proveedor.js
  api/src/routes/Productos/createProducto.js
  api/src/routes/Proveedores/getProveedor.js
  api/src/routes/Proveedores/putProveedor.js
Labels: enhancement

#98 correcciones en modelo categorías
  api/src/models/categorias/Categoria.js
Labels: enhancement

#99 ya wey, el filtrado arreglado
  client/src/Views/Tienda/Tienda.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#101 Correcciones de informacion
  api/src/models/productos_servicios/Producto_servicio.js
  api/src/routes/Productos/allProductos.js
  api/src/routes/Productos/createProducto.js
Labels: enhancement

#103 añadida funcion para que, al crear un comentario/reseña, se vincule d…
  api/src/models/comentarios_resenas/comentarios_resenas.json
  api/src/routes/comentariosResenas.js
Labels: enhancement

#104 Creacion Ruta Orden de compra
  api/src/app.js
  api/src/models/ordenesDeCompras/OrdenDeCompra.js
  api/src/routes/Productos/productoDetail.js
  api/src/routes/ordenDeCompra.js
Labels: enhancement

#107 Noelita
  client/src/Views/About/About.jsx
  client/src/Views/About/About.module.css
  client/src/Views/Contacto/Contacto.jsx
Labels: enhancement

#108 loader created
  client/src/Views/About/About.jsx
  client/src/Views/About/About.module.css
  client/src/Views/Contacto/Contacto.jsx
  client/src/Views/Faqs/Faqs.jsx
  client/src/Views/Faqs/Faqs.module.css
  client/src/components/Loader/Loader.jsx
  client/src/components/Loader/Loader.module.css
Labels: enhancement

#110 correcion y creacion de ruta especies
  api/src/app.js
  api/src/models/especies/Especie.js
  api/src/models/especies/especies.json
  api/src/models/provedores/Proveedor.js
  api/src/routes/Proveedores/putProveedor.js
  api/src/routes/especies.js
  api/src/routes/ordenDeCompra.js
Labels: enhancement

#112 Style: arregle el apellido de Petri
  client/src/Views/About/About.jsx
Labels: enhancement

#115 Carrito ajustado y Modal Generico
  client/src/App.jsx
  client/src/components/Cart/Cart.jsx
  client/src/components/ModalGenerico/ModalConsultaGenerico.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/hooks/useAuth.js
  client/src/hooks/useStore.js
Labels: enhancement

#117 NodeMailer funcionando y cosas validacion de Chona
  api/.gitignore
  api/README.md
  api/node_modules/.package-lock.json
  api/package-lock.json
  api/package.json
  api/src/account_transport.json
  api/src/app.js
  api/src/nodemailerConfig.js
  api/src/routes/nodeMailerRoute.js
  api/src/routes/usuarios.js
Labels: enhancement

#118 se comentaron lineas de auth para hacer llamados
  api/src/app.js
Labels: enhancement

#119 se agregaron categorias
  api/src/models/categorias/Categoria.js
Labels: enhancement

#120 Loader Implementado, Paginado armado
  api/node_modules/.package-lock.json
  client/package-lock.json
  client/package.json
  client/src/Views/Detail/Detail.jsx
  client/src/Views/Tienda/Tienda.jsx
  client/src/components/Paginate/Paginate.jsx
  client/src/hooks/useStore.js
  client/vite.config.js
Labels: enhancement

#121 Arreglado filtrado por valor
  client/src/Views/Tienda/Tienda.jsx
Labels: fix

#124 Noelita
  client/src/Views/Tienda/Tienda.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#125 mercado pago (base)
  api/node_modules/.package-lock.json
  api/package-lock.json
  api/package.json
  api/src/models/orders/order.js
  api/src/models/orders/order.json
  api/src/routes/mercadoPago.js
Labels: enhancement

#126 Modificando app y mercadoPago
  api/src/app.js
  api/src/routes/mercadoPago.js
Labels: enhancement

#127 Paginacion:
  client/src/Views/Tienda/Tienda.jsx
  client/src/hooks/useStore.js
Labels: enhancement
