Repository erikfille/PF-Henry, pull requests merged in 2023-04, with the labels that each got.

#130 Avance mercadoPago
  api/src/routes/mercadoPago.js
Labels: enhancement

#134 Noe denise
  api/node_modules/.bin/nodemon
  api/node_modules/.package-lock.json
  api/node_modules/nodemon/README.md
  api/node_modules/nodemon/bin/nodemon.js
  api/node_modules/nodemon/package.json
  api/package-lock.json
  api/package.json
  client/.env
  client/src/App.jsx
  client/src/Views/Checkout/Checkout.jsx
  client/src/Views/Comprar.jsx
  client/vite.config.js
Labels: bug

#135 Max
  client/src/Views/Servicios/Servicios.jsx
  client/src/Views/Tienda/Tienda.jsx
  client/src/Views/Tienda/Tienda.module.css
  client/src/components/Header/Header.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductCard/ProductCard.module.css
  client/src/components/ProductsContainer/ProductsContainer.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#150 emails
  api/src/emails/bienvenida.html
  api/src/emails/carrito.htm
  api/src/emails/compra.html
  api/src/emails/darsedebaja.html
  api/src/emails/error.html
  api/src/emails/nostock.html
  api/src/emails/promocion.html
  api/src/emails/registro.html
  api/src/emails/seguimiento.html
  api/src/emails/servicioalcliente.html
Labels: enhancement

#154 Limpie todo el tema de pasarelas de pago
  api/node_modules/.package-lock.json
  api/package-lock.json
  api/package.json
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Views/Checkout/Checkout.jsx
  client/src/Views/Comprar.jsx
Labels: enhancement

#155 Login completo
  client/src/components/Header/Header.jsx
  client/src/hooks/useAuth.js
Labels: enhancement

#157 Login y SignUp terminados
  client/src/components/CreateProduct/CreateProduct.jsx
  client/src/components/Header/Header.jsx
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/components/LoginWidget/validation.js
  client/src/hooks/useAuth.js
  client/src/mixins/auth.js
Labels: enhancement

#163 Brcik de mp renderizado funcional
  api/src/routes/mercadoPago.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/Brick.jsx
  client/src/Views/Checkout/Checkout.jsx
  client/src/statusBrick.jsx
Labels: enhancement

#166 Noelita
  client/src/Brick.jsx
  client/src/Views/Checkout/Checkout.jsx
  client/src/statusBrick.jsx
Labels: enhancement

#169 Petri
  api/node_modules/.package-lock.json
  api/src/models/mascotas/Mascota.js
  api/src/models/usuarios/Usuario.js
  api/src/routes/Productos/productoDetail.js
  api/src/routes/createMascota.js
  api/src/routes/usuarios.js
Labels: enhancement

#170 mercado pago nueva ruta
  api/src/routes/mercadoPago.js
Labels: fix

#172 FUNCIONA PAYPAL
  client/src/Stripe.jsx
  client/src/Views/Checkout/Brick2.jsx
  client/src/Views/Checkout/Checkout.jsx
  client/src/Views/Checkout/PayPal.jsx
Labels: enhancement

#174 Noe denise
  api/node_modules/.package-lock.json
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/Stripe.jsx
  client/src/Views/Checkout/Brick.jsx
  client/src/Views/Checkout/Brick2.jsx
  client/src/Views/Checkout/Checkout.jsx
  client/src/Views/Checkout/PayPal.jsx
  client/src/components/Cart/Cart.jsx
  client/src/statusBrick.jsx
Labels: enhancement

#181 altoqroq
  api/src/routes/comentariosResenas.js
  api/src/routes/createMascota.js
  api/src/routes/usuarios.js
Labels: enhancement

#182 arreglo de nodemailer
  api/src/account_transport.json
  api/src/app.js
  api/src/libs/emailFunctions.js
  api/src/nodemailerConfig.js
  api/src/routes/usuarios.js
Labels: enhancement, fix

#183 Petri36
  api/src/app.js
  api/src/models/productosVendido/productoVendido.js
  api/src/models/usuarios/Usuario.js
  api/src/routes/Productos/productoDetail.js
  api/src/routes/comprasUsuario.js
  api/src/routes/ordenDeCompra.js
Labels: enhancement

#185 Fix funcionalidad eliminar en checkout / Fix Funcion eliminar carrito al comprar
  .gitignore
  client/src/Views/Checkout/Checkout.jsx
  client/src/Views/Checkout/PayPal.jsx
Labels: fix

#189 comentarios y reseñas configurado
  api/.env
  api/src/routes/comentariosResenas.js
Labels: enhancement

#187 Max
  client/src/Views/Contacto/Contacto.jsx
  client/src/Views/Login/Login.jsx
  client/src/Views/Login/Login.module.css
  client/src/Views/Servicios/Servicios.jsx
  client/src/Views/Tienda/Tienda.jsx
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/Views/UserProfile/UserProfile.module.css
  client/src/components/Header/Header.jsx
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/components/PetData/PetData.jsx
  client/src/components/PetData/PetData.module.css
  client/src/components/PetsContainer/PetsContainer.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductCard/ProductCard.module.css
  client/src/components/ProductsContainer/ProductsContainer.jsx
Labels: fix

#193 perdon loco, hay que ver bien la logica del promedio
  api/src/routes/comentariosResenas.js
Labels: enhancement

#201 node mailer gmail
  api/src/routes/usuarios.js
Labels: enhancement, fix

#202 Petri36
  api/src/routes/createMascota.js
  api/src/routes/usuarios.js
Labels: enhancement

#203 promedio de rating produc segun reseñas
  api/src/libs/ratingFunctions.js
  api/src/models/comentarios_resenas/Comentario_resena.js
  api/src/models/productos_servicios/Producto_servicio.js
  api/src/routes/Productos/createProducto.js
  api/src/routes/comentariosResenas.js
Labels: enhancement

#204 Max
  api/node_modules/.package-lock.json
  client/src/Views/Checkout/Checkout.jsx
  client/src/Views/Checkout/Checkout.module.css
  client/src/components/Header/Header.jsx
  client/src/components/Header/Header.module.css
Labels: fix

#209 Limpieza de Cache
  .DS_Store
  api/node_modules/.package-lock.json
  api/src/routes/Productos/modifyingProducto.js
  client/.env
  client/package-lock.json
Labels: enhancement

#211 Max
  client/src/components/Loader/Loader.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/ProductDetail/ProductDetail.module.css
  client/src/components/ProductReviews/ProductReviews.jsx
Labels: fix

#213 Modales funcionando
  client/src/App.jsx
  client/src/Views/Checkout/PayPal.jsx
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/components/CreatePet/CreatePet.jsx
  client/src/components/ModalCreatePet/ModalCreatePet.jsx
  client/src/components/ModalCreatePet/ModalCreatePet.module.css
  client/src/components/ModalInfoGenerico/ModalInfoGenerico.jsx
  client/src/components/ModalInfoGenerico/ModalInfoGenerico.module.css
  client/src/components/ModalPetDetail/ModalPetDetail.jsx
  client/src/components/PetData/PetData.jsx
  client/src/components/PetsContainer/PetsContainer.jsx
  client/src/hooks/useStore.js
Labels: enhancement, fix

#215 pequeñas correciones en mascotas
  api/src/models/mascotas/Mascota.js
  api/src/routes/createMascota.js
Labels: fix

#216 Add form validate
  client/src/Views/Login/Login.jsx
  client/src/Views/Login/Login.module.css
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/components/LoginWidget/LoginWidget.module.css
  client/src/components/LoginWidget/validation.js
Labels: fix

#222 Ultrajeada de ruta a alquien q no voy a nombrar
  api/src/models/historialAnimal/Historial.js
  api/src/models/mascotas/Mascota.js
  api/src/routes/historialAnimal.js
  api/src/routes/usuarios.js
Labels: enhancement, fix

#223 Erik
  client/src/Views/UserProfile/userHelp.js
  client/src/components/CreatePet/CreatePet.jsx
  client/src/components/ProductReviews/ProductReviews.jsx
  client/src/hooks/useAuth.js
  client/src/hooks/useStore.js
Labels: enhancement

#225 Terminadas las reseñas
  client/src/Views/ProductDetail/Detail.jsx
  client/src/components/ProductReviews/ProductReviews.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#224 Max
  api/src/routes/createMascota.js
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/components/CreatePet/CreatePet.jsx
  client/src/components/CreatePet/CreatePet.module.css
  client/src/components/CreatePet/validation.js
  client/src/components/PetData/PetData.jsx
  client/src/components/PetData/PetData.module.css
  client/src/components/PetData/petHelp.js
  client/src/components/PetsContainer/PetsContainer.jsx
  client/src/components/ProductCard/ProductCard.jsx
Labels: fix

#233 Max
  client/src/Views/Home/Home.jsx
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/Views/UserProfile/UserProfile.module.css
  client/src/components/CreatePet/CreatePet.jsx
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/components/LoginWidget/LoginWidget.module.css
  client/src/components/ModalPetDetail/ModalPetDetail.jsx
  client/src/components/ModalPetDetail/ModalPetDetail.module.css
  client/src/components/ModalPetDetail/validation.js
  client/src/components/PetsContainer/PetsContainer.jsx
  client/src/hooks/useStore.js
Labels: fix

#234 Arreglado modal de estado de compra
  client/src/Views/Checkout/PayPal.jsx
  client/src/hooks/useStore.js
  client/vercel.json
Labels: fix

#237 Petri36
  api/src/app.js
  api/src/models/productosVendido/productoVendido.js
  api/src/routes/Productos/productoComprado.js
Labels: enhancement

#238 Fixed: El usuario no esta logueado y puede comprar
  client/src/components/Cart/Cart.jsx
  client/src/components/Cart/Cart.module.css
Labels: fix

#240 Conectados Animals y Categories al Dashboard de Admin
  client/src/App.jsx
  client/src/Views/DashboardAdmin/AdminDashboard.jsx
  client/src/Views/DashboardAdmin/DashAnimals/DashAnimals.jsx
  client/src/Views/DashboardAdmin/DashCategories/DashCategories.jsx
  client/src/Views/DashboardAdmin/DashProduct/DashProduct.jsx
  client/src/Views/DashboardAdmin/DashProvider/DashProvider.jsx
  client/src/Views/DashboardAdmin/DashUser/DashUser.jsx
  client/src/Views/DashboardAdmin/Sidebar/Sidebar.jsx
  client/src/Views/DashboardAdmin/helpers/Animals.js
  client/src/Views/DashboardAdmin/helpers/Categories.js
  client/src/Views/Tienda/Tienda.jsx
  client/src/hooks/useStore.js
Labels: enhancement, fix

#245 agregue un PUT para modificar los datos de la mascota
  api/src/routes/createMascota.js
Labels: enhancement

#247 Petri36
  api/src/models/categorias/Categoria.js
  api/src/models/especies/Especie.js
  api/src/routes/categorias.js
  api/src/routes/especies.js
Labels: enhancement

#248 Noe mil
  client/src/App.jsx
  client/src/Views/Faqs/Faqs.jsx
  client/src/Views/Terminos/Terminos.jsx
  client/src/components/Footer/Footer.jsx
Labels: enhancement

#250 DashboardAdmin Categorias casi terminado
  api/src/models/categorias/Categoria.js
  client/src/App.jsx
  client/src/Views/DashboardAdmin/DashCategories/DashCategories.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#253 Listo AdminDashboard/Categorias
  client/src/App.jsx
  client/src/Views/DashboardAdmin/DashAnimals/DashAnimals.jsx
  client/src/Views/DashboardAdmin/DashCategories/DashCategories.jsx
  client/src/Views/DashboardAdmin/DashCategories/ModalEditCategory.jsx
  client/src/Views/DashboardAdmin/DashCategories/ModalEditCategory.module.css
  client/src/hooks/useAuth.js
  client/src/hooks/useStore.js
Labels: enhancement

#256 Conectado AdminDashboard/Animales
  client/src/App.jsx
  client/src/Views/DashboardAdmin/DashAnimals/DashAnimals.jsx
  client/src/Views/DashboardAdmin/DashAnimals/ModalEditAnimals.jsx
  client/src/components/Header/Header.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#257 Max
  client/src/Views/Servicios/Servicios.jsx
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/components/Cart/Cart.jsx
  client/src/components/CreatePet/CreatePet.jsx
  client/src/components/CreatePet/validation.js
  client/src/components/Footer/Footer.jsx
  client/src/components/Footer/Footer.module.css
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/components/LoginWidget/LoginWidget.module.css
  client/src/components/LoginWidget/validation.js
  client/src/components/ModalPetDetail/ModalPetDetail.jsx
  client/src/components/ModalPetDetail/validation.js
  client/src/components/PetData/PetData.jsx
  client/src/components/PetsContainer/PetsContainer.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/ProductReviews/ProductReviews.jsx
  client/src/hooks/useStore.js
Labels: fix

#259 Noe mil
  client/src/App.jsx
  client/src/Views/Contacto/Contacto.jsx
  client/src/Views/Terminos/Terminos.jsx
  client/src/Views/Terminos/Terminos.module.css
  client/src/Views/Ubicacion/Ubicacion.jsx
  client/src/Views/Ubicacion/Ubicacion.module.css
  client/src/components/Footer/Footer.jsx
Labels: enhancement

#260 Styles den modales
  client/src/Views/DashboardAdmin/DashAnimals/DashAnimals.jsx
  client/src/Views/DashboardAdmin/DashAnimals/ModalEditAnimals.jsx
  client/src/Views/DashboardAdmin/DashCategories/DashCategories.jsx
  client/src/Views/DashboardAdmin/DashCategories/ModalEditCategory.jsx
  client/src/components/Header/Header.jsx
  client/src/hooks/useAuth.js
Labels: enhancement

#261 ruta getAllUsers y putUsers
  api/src/models/usuarios/Usuario.js
  api/src/routes/usuarios.js
Labels: enhancement

#262 agregue el DELETE de mascotas
  api/src/routes/createMascota.js
Labels: enhancement

#263 Petri36
  api/src/models/provedores/Proveedor.js
  api/src/routes/Productos/createProducto.js
  api/src/routes/Proveedores/putProveedor.js
  api/src/routes/comentariosResenas.js
Labels: enhancement

#264 Avances sobre DashUsers
  api/src/routes/usuarios.js
  client/src/Views/Checkout/PayPal.jsx
  client/src/Views/DashboardAdmin/AdminDashboard.jsx
  client/src/Views/DashboardAdmin/DashUser/DashUser.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#266 Agregado modal UserDetail al Admin Dashboard
  client/src/App.jsx
  client/src/Views/DashboardAdmin/DashUser/DashUser.jsx
  client/src/Views/DashboardAdmin/DashUser/ModalUserDetail.jsx
  client/src/Views/DashboardAdmin/DashUser/ModalUserDetail.module.css
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/components/Cart/Cart.jsx
  client/src/components/PetData/PetData.jsx
  client/src/components/PetsContainer/PetsContainer.jsx
  client/src/components/ProductCard/ProductCard.jsx
  client/src/components/ProductsContainer/ProductsContainer.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#268 AdminDashboard/Users Filtrados activos
  client/src/App.jsx
  client/src/Views/DashboardAdmin/AdminDashboard.jsx
  client/src/Views/DashboardAdmin/DashAnimals/DashAnimals.jsx
  client/src/Views/DashboardAdmin/DashAnimals/ModalEditAnimals.jsx
  client/src/Views/DashboardAdmin/DashCategories/DashCategories.jsx
  client/src/Views/DashboardAdmin/DashUser/DashUser.jsx
  client/src/Views/DashboardAdmin/DashUser/ModalUserEdit.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#274 Max
  client/src/components/Header/Header.jsx
  client/src/components/Header/Header.module.css
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/hooks/useAuth.js
  client/src/hooks/useStore.js
Labels: fix

#273 Santi
  api/src/app.js
  api/src/libs/emailFunctions.js
  api/src/libs/validateFunction.js
  api/src/models/usuarios/Usuario.js
  api/src/routes/usuarios.js
  api/src/routes/validacionToken.js
Labels: enhancement, fix

#275 Cambios varios y fixes
  client/src/App.jsx
  client/src/Views/DashboardAdmin/AdminDashboard.jsx
  client/src/Views/DashboardAdmin/DashAnimals/DashAnimals.jsx
  client/src/Views/DashboardAdmin/DashCategories/DashCategories.jsx
  client/src/Views/DashboardAdmin/DashProduct/DashProduct.jsx
  client/src/Views/DashboardAdmin/DashProvider/DashProvider.jsx
  client/src/Views/DashboardAdmin/DashUser/DashUser.jsx
  client/src/Views/DashboardAdmin/DashUser/ModalUserDetail.jsx
  client/src/Views/DashboardAdmin/DashUser/ModalUserEdit.jsx
  client/src/hooks/useAuth.js
  client/src/hooks/useStore.js
Labels: enhancement, fix

#277 Funcionalidad basica AdminDashboard/Proveedores
  client/src/Views/DashboardAdmin/DashAnimals/DashAnimals.jsx
  client/src/Views/DashboardAdmin/DashProduct/DashProduct.jsx
  client/src/Views/DashboardAdmin/DashProvider/DashProvider.jsx
  client/src/Views/DashboardAdmin/DashUser/DashUser.jsx
  client/src/hooks/useStore.js
Labels: enhancement

#279 AdminDashboard/Products finalizado
  api/src/routes/Productos/activeProducts.js
  api/src/routes/Productos/allProductos.js
  client/src/Views/ProductDetail/Detail.jsx
  client/src/Views/Tienda/Tienda.jsx
  client/src/components/Header/Header.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/hooks/useStore.js
Labels: enhancement, fix

#280 modificacion para asignar proveedores al usuario
  api/src/models/productos_servicios/Producto_servicio.js
  api/src/models/productos_servicios/productos_servicios.json
  api/src/models/provedores/Proveedor.js
  api/src/models/usuarios/Usuario.js
  api/src/routes/Proveedores/postProveedor.js
Labels: enhancement, fix

#281 Agregados modales al crear categorias y animales
  client/src/Views/DashboardAdmin/DashAnimals/DashAnimals.jsx
  client/src/Views/DashboardAdmin/DashCategories/DashCategories.jsx
  client/src/components/CreateProduct/CreateProduct.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
Labels: enhancement

#282 Noe mil
  client/src/Views/DashboardAdmin/DashUser/ModalUserDetail.jsx
  client/src/Views/DashboardAdmin/DashUser/ModalUserEdit.jsx
  client/src/Views/Ubicacion/Ubicacion.jsx
Labels: enhancement

#285 Max
  client/src/Views/Checkout/PayPal.jsx
  client/src/Views/DashboardAdmin/DashUser/DashUser.jsx
  client/src/Views/DashboardAdmin/Sidebar/Sidebar.jsx
  client/src/Views/Tienda/Tienda.jsx
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/ProductReviews/ProductReviews.jsx
  client/src/hooks/useStore.js
Labels: enhancement, fix

#286 estilos ok email
  api/src/emails/bienvenida.html
Labels: enhancement, fix

#288 toqueteando el front jejejej
  client/src/Views/DashboardAdmin/DashCategories/DashCategories.jsx
  client/src/Views/DashboardAdmin/DashProduct/DashProduct.jsx
  client/src/Views/DashboardAdmin/DashProvider/DashProvider.jsx
  client/src/Views/DashboardAdmin/DashUser/DashUser.jsx
Labels: fix

#291 correciones
  api/src/models/productosVendido/productoVendido.js
  api/src/routes/Productos/productoComprado.js
Labels: enhancement

#294 correcciones
  api/src/routes/Productos/stockProductos.js
  api/src/routes/validacionToken.js
Labels: enhancement

#296 Add PUT modifica stock al comprar
  client/src/Views/Checkout/Checkout.jsx
  client/src/Views/Checkout/PayPal.jsx
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/hooks/useStore.js
Labels: fix

#299 creado DELETE para comentarios
  api/src/routes/comentariosResenas.js
Labels: enhancement

#298 Noe mil
  client/src/Views/Faqs/Faqs.jsx
  client/src/components/CreatePet/CreatePet.jsx
  client/src/components/EditPet/EditPet.jsx
Labels: enhancement

#301 toqueteando el front jejejejejejejejeje
  client/src/components/Footer/Footer.jsx
Labels: enhancement

#300 Fix put stock, fix button agregar sin stock
  client/src/Views/Checkout/PayPal.jsx
  client/src/components/ModalInfoGenerico/ModalInfoGenerico.module.css
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/hooks/useStore.js
Labels: fix

#302 Muchas cosas y ahora podemos editar usuario
  client/src/App.jsx
  client/src/Views/DashboardAdmin/DashUser/DashUser.jsx
  client/src/Views/DashboardAdmin/DashUser/ModalUserDetail.jsx
  client/src/Views/DashboardAdmin/DashUser/ModalUserEdit.jsx
  client/src/Views/DashboardAdmin/DashUser/ModalUserEdit.module.css
  client/src/Views/DashboardAdmin/DashUser/validation.js
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/components/UploadWidget/UploadWidget.jsx
  client/src/hooks/useAuth.js
  client/src/hooks/useStore.js
Labels: enhancement

#303 desactivado proveedores
  client/src/App.jsx
  client/src/Views/DashboardAdmin/Sidebar/Sidebar.jsx
  client/src/components/Header/Header.jsx
Labels: enhancement

#304 creado DELETE para el historial animal
  api/src/routes/historialAnimal.js
Labels: enhancement

#305 ruta contacto
  api/src/app.js
  api/src/libs/emailFunctions.js
  api/src/routes/contactoForm.js
Labels: enhancement

#306 deshabilite el telefono del formulario de contacto
  client/src/Views/Contacto/Contacto.jsx
Labels: enhancement

#308 Noe mil
  client/package.json
  client/src/App.jsx
  client/src/components/ProductCard/ProductCard.jsx
Labels: enhancement

#307 Fix Modal edit
  client/src/components/EditPet/EditPet.jsx
Labels: fix

#310 cambios menores en paypal
  client/src/Views/Checkout/PayPal.jsx
Labels: enhancement

#311 cambio de ingles a español
  client/index.html
Labels: enhancement, fix

#313 Fix edit & create pets
  client/src/components/CreatePet/CreatePet.jsx
  client/src/components/EditPet/EditPet.jsx
  client/src/hooks/useStore.js
Labels: fix

#316 Max
  client/src/Views/Login/Login.jsx
  client/src/components/CreatePet/CreatePet.jsx
  client/src/components/Header/Header.jsx
  client/src/components/Header/Header.module.css
  client/src/components/ModalPetDetail/ModalPetDetail.jsx
Labels: bug

#317 Max
  client/src/Views/Contacto/Contacto.jsx
  client/src/Views/UserProfile/UserProfile.jsx
  client/src/components/LoginWidget/LoginWidget.jsx
  client/src/components/LoginWidget/LoginWidget.module.css
  client/src/components/ModalCreatePet/ModalCreatePet.module.css
  client/src/components/ModalPetDetail/ModalPetDetail.jsx
  client/src/components/ModalPetDetail/ModalPetDetail.module.css
  client/src/components/PetData/PetData.jsx
  client/src/hooks/useAuth.js
Labels: enhancement

#318 Noe mil
  client/src/App.jsx
  client/src/Views/Servicios/Servicios.jsx
  client/src/components/Header/Header.jsx
Labels: enhancement

#319 Fix formulario contacto
  client/src/Views/Contacto/Contacto.jsx
Labels: fix

#321 Fix ver password
  client/src/components/LoginWidget/LoginWidget.jsx
Labels: fix

#331 App v1.5.4
  client/src/components/Header/Header.jsx
  client/src/components/ProductReviews/ProductReviews.jsx
Labels: fix

#339 App v.1.5.15
  client/src/Views/DashboardAdmin/DashProduct/DashProduct.jsx
Labels: fix

#340 Fixed: Cart overlapped with login screen
  client/src/components/Cart/Cart.jsx
Labels: fix
